import React, { useState, useEffect } from "react";
import { TextField, Button, Typography } from "@mui/material";
import { useNavigate, useLocation } from "react-router-dom";

const LabEventsForm = () => {
  const navigate = useNavigate();
  const location = useLocation();

  // Extract the selected patient's ID and hospital admission ID from the location state
  const selectedPatientId = location.state
    ? location.state.selectedPatientId
    : "";
  const selectedHospitalAdmissionId = location.state
    ? location.state.hospitalAdmissionId
    : "";

  const [formData, setFormData] = useState({
    labevent_id: "", // Primary key, generated by the backend
    patientId: selectedPatientId,
    hospitalAdmissionId: selectedHospitalAdmissionId,
    specimen_id: "",
    item_id: "",
    order_provider_id: "",
    charttime: "",
    storetime: "",
    value: "",
    valuenum: "",
    valueuom: "",
    ref_range_lower: "",
    ref_range_upper: "",
    flag: "",
    priority: "",
    comments: "",
  });

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prevData) => ({
      ...prevData,
      [name]: value,
    }));
  };

  const labEventsData = {
    ...formData,
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    // Send the formData to the backend for further processing
    try {
      // Send the data to the backend using a POST request
      const response = await fetch("http://localhost:5000/api/labevents", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(labEventsData),
      });

      if (response.ok) {
        console.log("Lab Events form submitted successfully!");
        // Handle success (e.g., navigation or other actions)
      } else {
        console.error("Failed to submit Lab Events form:", response);
      }
    } catch (error) {
      console.error("Error submitting Lab Events form:", error);
    }
  };

  return (
    <form
      style={{
        margin: "30px",
        marginLeft: "10px",
        border: "2px solid blue",
        padding: "20px",
      }}
    >
      <Typography variant="h5" gutterBottom>
        Lab Events Form
      </Typography>
      <TextField
        label="Patient Id"
        name="patientId"
        value={formData.patientId}
        onChange={handleChange}
        fullWidth
        required
        style={{ marginBottom: "10px" }}
      />
      <TextField
        label="Hospital Admission ID"
        name="hospitalAdmissionId"
        value={formData.hospitalAdmissionId}
        fullWidth
        disabled // Prevent manual editing
        style={{ marginBottom: "10px" }}
      />
      <TextField
        label="Specimen ID"
        name="specimen_id"
        value={formData.specimen_id}
        onChange={handleChange}
        fullWidth
        required
        style={{ marginBottom: "10px" }}
      />
      <TextField
        label="Item ID"
        name="item_id"
        value={formData.item_id}
        onChange={handleChange}
        fullWidth
        required
        style={{ marginBottom: "10px" }}
      />
      {/* Add more fields for the rest of the form data */}
      <TextField
        label="Order Provider ID"
        name="order_provider_id"
        value={formData.order_provider_id}
        onChange={handleChange}
        fullWidth
        required
        style={{ marginBottom: "10px" }}
      />
      <TextField
        label="Chart Time"
        name="charttime"
        value={formData.charttime}
        type="datetime-local" // You can adjust the input type as needed
        onChange={handleChange}
        fullWidth
        required
        style={{ marginBottom: "10px" }}
      />
      <TextField
        label="Store Time"
        name="storetime"
        value={formData.storetime}
        type="datetime-local" // You can adjust the input type as needed
        onChange={handleChange}
        fullWidth
        required
        style={{ marginBottom: "10px" }}
      />
      <TextField
        label="Value"
        name="value"
        value={formData.value}
        onChange={handleChange}
        fullWidth
        required
        style={{ marginBottom: "10px" }}
      />
      <TextField
        label="Value Number"
        name="valuenum"
        value={formData.valuenum}
        onChange={handleChange}
        fullWidth
        required
        style={{ marginBottom: "10px" }}
      />
      <TextField
        label="Value Unit of Measure"
        name="valueuom"
        value={formData.valueuom}
        onChange={handleChange}
        fullWidth
        required
        style={{ marginBottom: "10px" }}
      />
      <TextField
        label="Reference Range Lower"
        name="ref_range_lower"
        value={formData.ref_range_lower}
        onChange={handleChange}
        fullWidth
        required
        style={{ marginBottom: "10px" }}
      />
      <TextField
        label="Reference Range Upper"
        name="ref_range_upper"
        value={formData.ref_range_upper}
        onChange={handleChange}
        fullWidth
        required
        style={{ marginBottom: "10px" }}
      />
      <TextField
        label="Flag"
        name="flag"
        value={formData.flag}
        onChange={handleChange}
        fullWidth
        required
        style={{ marginBottom: "10px" }}
      />
      <TextField
        label="Priority"
        name="priority"
        value={formData.priority}
        onChange={handleChange}
        fullWidth
        required
        style={{ marginBottom: "10px" }}
      />
      <TextField
        label="Comments"
        name="comments"
        value={formData.comments}
        onChange={handleChange}
        fullWidth
        required
        style={{ marginBottom: "10px" }}
      />

      <div style={{ display: "flex", justifyContent: "space-between" }}>
        <Button variant="contained" color="primary" onClick={handleSubmit}>
          Submit
        </Button>
      </div>
    </form>
  );
};

export default LabEventsForm;
